apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ5b3VyLXJlZ2lzdHJ5LmlvIjp7InVzZXJuYW1lIjoieW91ci11c2VybmFtZSIsInBhc3N3b3JkIjoieW91ci1wYXNzd29yZCIsImVtYWlsIjoieW91ci1lbWFpbCIsImF1dGgiOiJlVzkxY2kxMWMyVnlibUZ0WlRwNWIzVnlMWEJoYzNOM2IzSmsifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: api-service
type: kubernetes.io/dockerconfigjson
